CREATE TABLE `data_set_detail_areas` (
	`id` integer PRIMARY KEY NOT NULL,
	`data_set_result_id` integer,
	`reference_date` text NOT NULL,
	`area_group` text,
	`young_population_ratio` real,
	`elderly_population_ratio` real,
	`total_building_count` integer,
	`vacant_house_count` integer,
	`area` real,
	`geometry` text NOT NULL,
	`key_code` text,
	`predicted_probability` real,
	`vacant_house_count_05` integer,
	`vacant_house_count_10` integer,
	`vacant_house_count_15` integer,
	`vacant_house_count_20` integer,
	`vacant_house_count_25` integer,
	`vacant_house_count_30` integer,
	`vacant_house_count_35` integer,
	`vacant_house_count_40` integer,
	`vacant_house_count_45` integer,
	`vacant_house_count_50` integer,
	`vacant_house_count_55` integer,
	`vacant_house_count_60` integer,
	`vacant_house_count_65` integer,
	`vacant_house_count_70` integer,
	`vacant_house_count_75` integer,
	`vacant_house_count_80` integer,
	`vacant_house_count_85` integer,
	`vacant_house_count_90` integer,
	`vacant_house_count_95` integer,
	`predicted_probability_05` real,
	`predicted_probability_10` real,
	`predicted_probability_15` real,
	`predicted_probability_20` real,
	`predicted_probability_25` real,
	`predicted_probability_30` real,
	`predicted_probability_35` real,
	`predicted_probability_40` real,
	`predicted_probability_45` real,
	`predicted_probability_50` real,
	`predicted_probability_55` real,
	`predicted_probability_60` real,
	`predicted_probability_65` real,
	`predicted_probability_70` real,
	`predicted_probability_75` real,
	`predicted_probability_80` real,
	`predicted_probability_85` real,
	`predicted_probability_90` real,
	`predicted_probability_95` real,
	`unestimable_count` integer,
	`created_at` text DEFAULT (CURRENT_TIMESTAMP) NOT NULL,
	`updated_at` text DEFAULT (CURRENT_TIMESTAMP) NOT NULL
);
--> statement-breakpoint
CREATE TABLE `data_set_detail_buildings` (
	`id` integer PRIMARY KEY NOT NULL,
	`data_set_result_id` integer,
	`household_code` text,
	`normalized_address` text,
	`area_group` text,
	`reference_date` text NOT NULL,
	`household_size` integer,
	`residence_duration` integer,
	`water_supply_number` text,
	`water_disconnection_flag` integer,
	`max_water_usage` real,
	`avg_water_usage` real,
	`total_water_usage` real,
	`structure_name` text,
	`has_water_supply` integer,
	`has_juki_registry` integer,
	`has_touki_registry` integer,
	`fid` text,
	`bldg_class` text,
	`bldg_geometry` text,
	`measured_height` real,
	`measured_height_uom` text,
	`src_scale` text,
	`geometry_src_desc` text,
	`thematic_src_desc` text,
	`lod1_height_type` text,
	`building_id` text,
	`prefecture` text,
	`bldg_city` text,
	`bldg_description` text,
	`inland_flooding_risk_desc` text,
	`inland_flooding_risk_rank` integer,
	`inland_flooding_risk_depth` real,
	`inland_flooding_risk_depth_uom` text,
	`river_flooding_risk_description` text,
	`river_flooding_risk_rank` integer,
	`river_flooding_risk_depth` real,
	`river_flooding_risk_depth_uom` text,
	`landslide_risk_description` text,
	`appearance_src_desc` text,
	`residence_id` text,
	`name` text,
	`predicted_label` integer,
	`predicted_probability` real,
	`predicted_label_05` integer,
	`predicted_label_10` integer,
	`predicted_label_15` integer,
	`predicted_label_20` integer,
	`predicted_label_25` integer,
	`predicted_label_30` integer,
	`predicted_label_35` integer,
	`predicted_label_40` integer,
	`predicted_label_45` integer,
	`predicted_label_50` integer,
	`predicted_label_55` integer,
	`predicted_label_60` integer,
	`predicted_label_65` integer,
	`predicted_label_70` integer,
	`predicted_label_75` integer,
	`predicted_label_80` integer,
	`predicted_label_85` integer,
	`predicted_label_90` integer,
	`predicted_label_95` integer,
	`max_age` integer,
	`buildingtype_determination_not_possible_flag` integer,
	`days_since_registration_event` integer,
	`address` text,
	`area_classification_type` text,
	`bldg_dm_attribute` text,
	`bldg_facility_attribute` text,
	`bldg_facility_id_attribute` text,
	`bldg_facility_type_attribute` text,
	`bldg_real_estate_id_attribute` text,
	`bldg_usecase_attribute` text,
	`bounded_by` text,
	`building_data_quality_attribute` text,
	`building_detail_attribute` text,
	`building_disaster_risk_attribute` text,
	`hightide_risk_depth` real,
	`hightide_risk_depth_uom` text,
	`hightide_risk_description` text,
	`hightide_risk_rank` integer,
	`landslide_risk_areatype` text,
	`river_flooding_risk_admin_type` text,
	`tsunami_risk_depth` real,
	`tsunami_risk_depth_uom` text,
	`tsunami_risk_description` text,
	`tsunami_risk_rank` text,
	`building_footprint_area` real,
	`building_footprint_area_uom` text,
	`building_height` real,
	`building_height_uom` text,
	`building_id_attribute` text,
	`building_structure_type` text,
	`consists_of_building_part` text,
	`bldg_creation_date` text,
	`districts_and_zones_type` text,
	`function_plateau` text,
	`generic_attribute` text,
	`ifc_building_attribute` text,
	`indoor_building_attribute` text,
	`interior_building_installation` text,
	`interior_room` text,
	`key_value_pair_attribute` text,
	`large_customer_facility_attribute` text,
	`lod_type` text,
	`org_usage2` text,
	`outer_building_installation` text,
	`parent_type` text,
	`roof_type` text,
	`storey_heights_above_ground` real,
	`storey_heights_below_ground` real,
	`storeys_above_ground` integer,
	`storeys_below_ground` integer,
	`survey_year` integer,
	`termination_date` text,
	`total_floor_area` real,
	`total_floor_area_uom` text,
	`year_of_construction` integer,
	`year_of_demolition` integer,
	`key_code` text,
	`building_type` text,
	`water_startdate` text,
	`water_enddate` text,
	`building_use` text,
	`river_flooding_risk_scale` text,
	`river_flooding_risk_duration` text,
	`river_flooding_risk_duration_uom` text,
	`lon_geocoding` real,
	`lat_geocoding` real,
	`level_geocoding` text,
	`confidency_geocoding` text,
	`address_for_building_type` text,
	`latitude_for_building_type` real,
	`longitude_for_building_type` real,
	`num_deaths` integer,
	`num_inmigrants` integer,
	`num_outmigrants_relocations` integer,
	`num_cancellations` integer,
	`num_householdsize_after_changes` integer,
	`years_water_closure` real,
	`average_waterusage_person` real,
	`change_rate_waterusage_over_last4months` real,
	`flag_zero_usage_over4consecutivemonths` integer,
	`flag_concreteblock` integer,
	`flag_brick` integer,
	`flag_reinforcedconcreteconstruction` integer,
	`flag_steelframe` integer,
	`flag_wood` integer,
	`flag_earthen` integer,
	`flag_otherstructures` integer,
	`flag_inheritance` integer,
	`flag_gift` integer,
	`flag_sale` integer,
	`flag_seizure` integer,
	`date_inheritance` text,
	`has_geocoding` integer,
	`bldg_id` text,
	`members_under_15` integer,
	`members_over_65` integer,
	`registration_date` text,
	`date_registration_event` text,
	`waterusage_11to12m_ago` real,
	`waterusage_9to10m_ago` real,
	`waterusage_7to8m_ago` real,
	`waterusage_5to6m_ago` real,
	`waterusage_3to4m_ago` real,
	`waterusage_1to2m_ago` real,
	`created_at` text DEFAULT (CURRENT_TIMESTAMP) NOT NULL,
	`updated_at` text DEFAULT (CURRENT_TIMESTAMP) NOT NULL
);
--> statement-breakpoint
CREATE INDEX `idx_buildings_filter` ON `data_set_detail_buildings` (`data_set_result_id`,`reference_date`,`area_group`);--> statement-breakpoint
CREATE INDEX `idx_buildings_spatial` ON `data_set_detail_buildings` (`lat_geocoding`,`lon_geocoding`);--> statement-breakpoint
CREATE TABLE `data_set_results` (
	`id` integer PRIMARY KEY NOT NULL,
	`title` text,
	`created_at` text DEFAULT (CURRENT_TIMESTAMP) NOT NULL,
	`updated_at` text DEFAULT (CURRENT_TIMESTAMP) NOT NULL
);
--> statement-breakpoint
CREATE TABLE `job_results` (
	`id` integer PRIMARY KEY NOT NULL,
	`job_id` integer NOT NULL,
	`file_path` text NOT NULL,
	`created_at` text DEFAULT (CURRENT_TIMESTAMP) NOT NULL,
	`updated_at` text DEFAULT (CURRENT_TIMESTAMP) NOT NULL,
	FOREIGN KEY (`job_id`) REFERENCES `jobs`(`id`) ON UPDATE no action ON DELETE no action
);
--> statement-breakpoint
CREATE TABLE `job_tasks` (
	`id` integer PRIMARY KEY NOT NULL,
	`job_id` integer NOT NULL,
	`progress_percent` text,
	`preprocess_type` text,
	`error_code` text,
	`error_msg` text,
	`result` text,
	`finished_at` text DEFAULT (CURRENT_TIMESTAMP),
	`created_at` text DEFAULT (CURRENT_TIMESTAMP) NOT NULL,
	`updated_at` text DEFAULT (CURRENT_TIMESTAMP) NOT NULL,
	FOREIGN KEY (`job_id`) REFERENCES `jobs`(`id`) ON UPDATE no action ON DELETE no action
);
--> statement-breakpoint
CREATE TABLE `jobs` (
	`id` integer PRIMARY KEY NOT NULL,
	`status` text,
	`type` text,
	`process_id` integer,
	`is_named` integer NOT NULL,
	`parameters` text NOT NULL,
	`created_at` text DEFAULT (CURRENT_TIMESTAMP) NOT NULL,
	`updated_at` text DEFAULT (CURRENT_TIMESTAMP) NOT NULL
);
--> statement-breakpoint
CREATE TABLE `model_files` (
	`id` integer PRIMARY KEY NOT NULL,
	`file_name` text,
	`note` text,
	`file_path` text,
	`created_by_job_id` integer NOT NULL,
	`created_at` text DEFAULT (CURRENT_TIMESTAMP) NOT NULL,
	`updated_at` text DEFAULT (CURRENT_TIMESTAMP) NOT NULL,
	FOREIGN KEY (`created_by_job_id`) REFERENCES `jobs`(`id`) ON UPDATE no action ON DELETE no action
);
--> statement-breakpoint
CREATE TABLE `normalized_data_sets` (
	`id` integer PRIMARY KEY NOT NULL,
	`file_name` text,
	`file_path` text NOT NULL,
	`job_results_id` integer,
	`created_at` text DEFAULT (CURRENT_TIMESTAMP) NOT NULL,
	`updated_at` text DEFAULT (CURRENT_TIMESTAMP) NOT NULL,
	FOREIGN KEY (`job_results_id`) REFERENCES `job_results`(`id`) ON UPDATE no action ON DELETE no action
);
--> statement-breakpoint
CREATE TABLE `raw_data_sets` (
	`id` integer PRIMARY KEY NOT NULL,
	`file_name` text NOT NULL,
	`file_path` text NOT NULL,
	`created_at` text DEFAULT (CURRENT_TIMESTAMP) NOT NULL,
	`updated_at` text DEFAULT (CURRENT_TIMESTAMP) NOT NULL
);
--> statement-breakpoint
CREATE TABLE `result_sheets` (
	`id` integer PRIMARY KEY NOT NULL,
	`workbook_id` integer,
	`title` text,
	`created_at` text DEFAULT (CURRENT_TIMESTAMP) NOT NULL,
	`updated_at` text DEFAULT (CURRENT_TIMESTAMP) NOT NULL
);
--> statement-breakpoint
CREATE TABLE `result_views` (
	`id` integer PRIMARY KEY NOT NULL,
	`sheet_id` integer,
	`data_set_result_id` integer,
	`title` text,
	`unit` text,
	`style` text,
	`layoutIndex` integer,
	`parameters` text NOT NULL,
	`created_at` text DEFAULT (CURRENT_TIMESTAMP) NOT NULL,
	`updated_at` text DEFAULT (CURRENT_TIMESTAMP) NOT NULL
);
--> statement-breakpoint
CREATE TABLE `users` (
	`id` integer PRIMARY KEY NOT NULL,
	`name` text
);
--> statement-breakpoint
CREATE TABLE `workbooks` (
	`id` integer PRIMARY KEY NOT NULL,
	`title` text,
	`created_at` text DEFAULT (CURRENT_TIMESTAMP) NOT NULL,
	`updated_at` text DEFAULT (CURRENT_TIMESTAMP) NOT NULL
);
