import { type ipcMain } from "electron";
import path from "path";
import { appInfoHandler } from "../features/app-info/ipc-handler";
import { evaluateData } from "../features/evaluation/ipc";
import {
  selectModelFiles,
  selectModelThreshold,
  updateModelFiles,
  deleteModelFiles,
  createModelFiles,
  insertModelFile,
  buildModel,
} from "../features/model/ipc";
import {
  selectJobs,
  selectJobsWithPagination,
  selectJob,
  selectJobTasks,
  selectJobLog,
  selectJobResults,
  selectProbabilityBins,
  deleteJob,
  resolveJobFileNames,
} from "../features/job/ipc";
import {
  createDraftJob,
  updateDraftJob,
  selectDraftJob,
  preValidateDataset,
} from "../features/normalization/ipc";
import {
  selectTutorialState,
  updateTutorialState,
  isDraftReferencedByGuide,
  selectGuideNames,
} from "../features/tutorial/ipc";
import {
  createWorkbooks,
  selectWorkbooks,
  selectWorkbook,
  deleteWorkbook,
  insertResultSheets,
  selectResultSheets,
  updateResultSheets,
  deleteResultSheet,
} from "../features/workbook/ipc";
import {
  selectDataSetResults,
  filterDataSetForTable,
  selectRawDatasets,
  insertRawDatasets,
  selectNormalizedDataSets,
  insertNormalizedDatasets,
  selectRawDataset,
  selectNormalizedDataSet,
  selectDataSetResult,
  readDatasetFile,
  updateRawDataset,
  updateNormalizedDataset,
  updateDataSetResult,
  deleteRawDataset,
  deleteNormalizedDataset,
  deleteDataSetResult,
  readDatasetColumns,
  readDatasetColumnValues,
  createNormalizedDatasets,
  selectNormalizedDatasetWithFilePath,
  selectNormalizedDatasetGeometrySources,
  selectRawDatasetWithFilePath,
  createResultDatasets,
  selectDataSetCount,
  selectDataSetFileStats,
} from "../features/dataset/ipc";
import {
  selectAreasInBatches,
  selectResultViews,
  insertResultViews,
  updateResultViews,
  readResultViews,
  selectResultView,
  deleteResultView,
  selectAreaGroups,
  updateResultViewsLayoutIndex,
  selectBuildingsWithPagination,
  selectAreasWithPagination,
  selectBuildingPreview,
  selectBoundaryBuildings,
  fetchChartData,
  updateMapCenter,
  selectMapCenter,
  selectBuildingsChunk,
  selectBuildingsLastId,
  selectBuildingsCount,
  selectBuilding,
  selectBuildingByReferenceDate,
  selectBuildingsViewportChunk,
  selectBuildingsViewportCount,
  selectAreasViewportChunk,
  selectAreasViewportCount,
  selectArea,
  selectAreaByReferenceDate,
  selectAreaProbabilityMax,
  exportChartCsv,
  selectEstimationThreshold,
  selectEstimationParameters,
  selectViewTemplates,
  insertViewTemplate,
  applyViewTemplate,
  updateViewTemplate,
  deleteViewTemplate,
} from "../features/bi/ipc";
import { selectReferenceDates } from "./select-reference-dates";
import { saveFile } from "./save-file";
import { execE001 } from "./ml/exec-e001";
import { execIF005JoinCheck } from "./ml/exec-if005-join-check";
import { exportData } from "./ml/export-data";
import { getAppInfo } from "./get-app-info";
import { writeRendererLogs } from "./write-renderer-logs";
import { showOpenCsvDialog } from "./show-open-csv-dialog";
import { showErrorDialog } from "./show-error-dialog";

export const ipcMainListeners = {
  createWorkbooks,
  selectWorkbooks,
  selectWorkbook,
  selectResultSheets,
  insertResultSheets,
  deleteResultSheet,
  selectDataSetResults,
  updateResultSheets,
  selectResultViews,
  insertResultViews,
  updateResultViews,
  readResultViews,
  readDatasetColumns,
  readDatasetColumnValues,
  selectResultView,
  deleteResultView,
  filterDataSetForTable,
  selectReferenceDates,
  selectAreaGroups,
  selectAreasInBatches,
  deleteWorkbook,
  updateResultViewsLayoutIndex,
  selectRawDatasets,
  insertRawDatasets,
  saveFile,
  selectNormalizedDataSets,
  insertNormalizedDatasets,
  selectRawDataset,
  selectNormalizedDataSet,
  selectDataSetResult,
  readDatasetFile,
  selectModelFiles,
  selectModelThreshold,
  updateRawDataset,
  updateNormalizedDataset,
  updateDataSetResult,
  deleteRawDataset,
  deleteNormalizedDataset,
  deleteDataSetResult,
  updateModelFiles,
  deleteModelFiles,
  selectJobs,
  selectJobTasks,
  selectJobLog,
  buildModel,
  evaluateData,
  execE001,
  execIF005JoinCheck,
  selectBuildingsWithPagination,
  selectAreasWithPagination,
  selectJobResults,
  selectProbabilityBins,
  createNormalizedDatasets,
  createModelFiles,
  insertModelFile,
  selectBuildingPreview,
  selectBoundaryBuildings,
  exportData,
  selectJob,
  selectNormalizedDatasetWithFilePath,
  selectNormalizedDatasetGeometrySources,
  selectRawDatasetWithFilePath,
  selectJobsWithPagination,
  fetchChartData,
  deleteJob,
  createResultDatasets,
  selectDataSetCount,
  selectDataSetFileStats,
  updateMapCenter,
  selectMapCenter,
  selectBuildingsChunk,
  selectBuildingsLastId,
  selectBuildingsCount,
  selectBuilding,
  selectBuildingByReferenceDate,
  selectBuildingsViewportChunk,
  selectBuildingsViewportCount,
  selectAreasViewportChunk,
  selectAreasViewportCount,
  selectArea,
  selectAreaByReferenceDate,
  selectAreaProbabilityMax,
  writeRendererLogs,
  getAppInfo,
  appInfo: appInfoHandler,
  exportChartCsv,
  showOpenCsvDialog,
  showErrorDialog,
  selectEstimationThreshold,
  selectEstimationParameters,
  createDraftJob,
  updateDraftJob,
  selectDraftJob,
  preValidateDataset,
  selectTutorialState,
  updateTutorialState,
  isDraftReferencedByGuide,
  selectGuideNames,
  resolveJobFileNames,
  selectViewTemplates,
  insertViewTemplate,
  applyViewTemplate,
  updateViewTemplate,
  deleteViewTemplate,
};

export const binaryPath = (name: string): string => {
  const isDev = process.env.NODE_ENV === "development";
  const _binaryPath = path.resolve(__dirname, "../../../ml/dist", name);
  return isDev ? _binaryPath : path.join(process.resourcesPath, "dist", name);
};

export type IpcMainListener = Parameters<typeof ipcMain.handle>[1];
